### ISSUE TITLE
ParseException on "stale" parameter when dealing with non RFC compliant server implementation

### ISSUE THREAD

**Issue by sebphil** [vzhn/netty-http-authenticator#11]
Hi!

I'm having a **ParseException** with message `"expected: true | false"` when trying to parse the WWW-Authenticate header sent to me by the server I'm trying to connect to. As it turns out, this server does not exactly comply with [RFC 7616](https://tools.ietf.org/html/rfc7616) which states that:

> For historical reasons, a sender MUST NOT generate the quoted string syntax values for the following parameters: stale and algorithm.

And of course, the server is sending me a quoted string as a value for the stale parameter.

The RFC also states that:

> If stale is false, or anything other than true, or the stale parameter is not present, the username and/or password are invalid, and new values MUST be obtained.

So I thought it might be a good idea to improve the parsing of the stale parameter by using the following rule:

- if value is (unquoted) true or (quoted) "true" then stale is true
- any other value (including false, "false" or really anything else) means stale is false

I will provide a PR fixing this in a few minutes.

**Comment by vzhn** [comment]
Thank you!
new release is ready: https://github.com/vzhn/netty-http-authenticator/releases/tag/v1.5

**Comment by sebphil** [comment]
thank you for the release!
