### ISSUE TITLE
Default Digest Algoritm

### ISSUE THREAD

**Issue by jeremyrumpf** [vzhn/netty-http-authenticator#8]
I was using your code to implement a connector to some security cameras. The DigestNettyHttpAuthenticator was failling (I used the NettyClientDemo as a template).

These cameras are sending an auth header like:

WWW-Authenticate : Digest realm="Login to 197463ea38eeb7da61115441df24f33a", qop="auth", nonce="2025753977", opaque="b07caf2c649461aadfcd0597f8d545b1e0f2bbf0"

Notice it contains no **algorithm** specification. I added a default algorithm (MD5) selection at the end of ChallengeResponseParser.readDigestChallenge() and it started working.

`        if (challenge.getAlgorithm() == null)
            challenge.addAlgorithm(DigestAlgorithm.MD5);
`

Not sure if this is the correct thing to do, but it is working for me. Without this it would swallow an exception in Ha1.hash() as the digest instance was null.

Regards

#9

**Comment by vzhn** [comment]
@sebphil 
Implemented in this commit: https://github.com/vzhn/netty-http-authenticator/commit/9a4441a80f49d64a88296e88dca86e41d919f196

Please check if it works

**Comment by sebphil** [comment]
@vzhn I get a NullPointerException on Digester.java line 106, I guess the default algorithm needs to be set on Digester too

**Comment by vzhn** [comment]
@sebphil we could assume that qop is `QopOptions.AUTH` when it is null. Please check next update

**Comment by vzhn** [comment]
@sebphil ready. please check

**Comment by sebphil** [comment]
your last commit reverted the previous one, I guess this was unintentional...

**Comment by vzhn** [comment]
Awww, yes it is.

**Comment by vzhn** [comment]
Now it should be OK

**Comment by vzhn** [comment]
@sebphil you're right, so this fix should work, I guess https://github.com/vzhn/netty-http-authenticator/commit/3624e89b0fa4538fdaf7f18ff6eb9dfb959a073b

**Comment by sebphil** [comment]
@vzhn yes I tried that too and it looks like it works. I was testing your lib using https://jigsaw.w3.org/HTTP/ but this service does not seem to support the full range of RFC 2617 so I had to remove algorithm, cnonce and nc from the header to make it work. Anyway, the real service I will call should handle the spec correctly, so I assume your lib should work now.

Unfortunately, to test the latest snapshot of your lib against the real service I'm supposed to call, I have to push it on my company's private repository, so this will have to wait until tomorrow.

**Comment by vzhn** [comment]
Ok, Let's wait.

**Comment by sebphil** [comment]
@vzhn Thank you very much for the release, I was able to test the authentication to the actual service I'm supposed to call, using version 1.2 of your lib. I'm still having trouble getting the authentication to succeed, so I'm going to investigate that part and I might need to open another issue. Next time I'll provide a PR ;)

A quick note thought: it looks like the NPE on Digester.java line 106 came back, so I had to keep the workaround I mentioned earlier. If I need to raise another issue, I will include the fix to this one in the PR too, unless you want to fix it yourself right away.

**Comment by vzhn** [comment]
Thank you! I tried to implement suggested workaround in last two commits. Please check new version 1.4.

**Comment by sebphil** [comment]
@vzhn thank you! Version 1.4 looks fine now. Unfortunately, I'm still unable to authenticate to my service, but as far as I can tell there's nothing wrong in the Authorization header generated by your lib. I'll have to investigate this, it might be an issue in the service I'm calling itself. Thanks again!
